//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace AcmeCorpEntities
{
    public partial class AcmeCorpContainer : ObjectContext
    {
        public const string ConnectionString = "name=AcmeCorpContainer";
        public const string ContainerName = "AcmeCorpContainer";
    
        #region Constructors
    
        public AcmeCorpContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public AcmeCorpContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public AcmeCorpContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<PurchaseOrder> PurchaseOrders
        {
            get { return _purchaseOrders  ?? (_purchaseOrders = CreateObjectSet<PurchaseOrder>("PurchaseOrders")); }
        }
        private ObjectSet<PurchaseOrder> _purchaseOrders;
    
        public ObjectSet<PurchaseOrderLineItem> PurchaseOrderLineItems
        {
            get { return _purchaseOrderLineItems  ?? (_purchaseOrderLineItems = CreateObjectSet<PurchaseOrderLineItem>("PurchaseOrderLineItems")); }
        }
        private ObjectSet<PurchaseOrderLineItem> _purchaseOrderLineItems;
    
        public ObjectSet<Supplier> Suppliers
        {
            get { return _suppliers  ?? (_suppliers = CreateObjectSet<Supplier>("Suppliers")); }
        }
        private ObjectSet<Supplier> _suppliers;

        #endregion
    }
}
