//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace AcmeCorpEntities
{
    public partial class PurchaseOrderLineItem
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual decimal Price
        {
            get;
            set;
        }
    
        public virtual int Quantity
        {
            get;
            set;
        }
    
        public virtual int PurchaseOrderId
        {
            get { return _purchaseOrderId; }
            set
            {
                if (_purchaseOrderId != value)
                {
                    if (PurchaseOrder != null && PurchaseOrder.Id != value)
                    {
                        PurchaseOrder = null;
                    }
                    _purchaseOrderId = value;
                }
            }
        }
        private int _purchaseOrderId;
    
        public virtual int Position
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual PurchaseOrder PurchaseOrder
        {
            get { return _purchaseOrder; }
            set
            {
                if (!ReferenceEquals(_purchaseOrder, value))
                {
                    var previousValue = _purchaseOrder;
                    _purchaseOrder = value;
                    FixupPurchaseOrder(previousValue);
                }
            }
        }
        private PurchaseOrder _purchaseOrder;

        #endregion
        #region Association Fixup
    
        private void FixupPurchaseOrder(PurchaseOrder previousValue)
        {
            if (PurchaseOrder != null)
            {
                if (PurchaseOrderId != PurchaseOrder.Id)
                {
                    PurchaseOrderId = PurchaseOrder.Id;
                }
            }
        }

        #endregion
    }
}
