//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFStarter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.Songs = new HashSet<Track>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int ArtistId { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual ICollection<Track> Songs { get; set; }
    }
}
