//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Pubs : DbContext
    {
        public Pubs()
            : base("name=Pubs")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Publisher> Publishers { get; set; }
        public DbSet<Title> Titles { get; set; }
    
        public virtual int ApplyPercentagePriceChangeToTitle(Nullable<decimal> percentageRise)
        {
            var percentageRiseParameter = percentageRise.HasValue ?
                new ObjectParameter("percentageRise", percentageRise) :
                new ObjectParameter("percentageRise", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ApplyPercentagePriceChangeToTitle", percentageRiseParameter);
        }
    }
}
