//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string PubId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<int> Royalty { get; set; }
        public Nullable<int> YtdSales { get; set; }
        public string Notes { get; set; }
        public System.DateTime PubDate { get; set; }
    
        public virtual Publisher Publisher { get; set; }
    }
}
